### ISSUE TITLE
logger.Logger interface not compatible with logrus.FieldLogger interface

### ISSUE THREAD

**Issue by jh125486** [gobuffalo/logger#10]
I'm not certain if this was intentional or not, but only three methods are missing:

- `WithError(err error) *Entry`
- `Warningf(format string, args ...interface{})`
- `Panicf(format string, args ...interface{})`

Since `logger.FieldLogger` is just a wrapped `logrus.Logger`, would it be a problem to add these three methods to the interface definition?

**Comment by sio4** [comment]
maybe the reason developers made things as wrappers, adding "another" layer between the users and the thing inside the wrapper regardless of what it is, might be they want to have a different interface/abstraction so they can keep the interface as the same even if they changed the thing inside. I don't think the wrapper has to have the same interfaces as the thing inside.

I would like to close this issue for now, but please feel free to reopen it, and let us know if there is some specific issue with them or any suggestions about the interface of the logger.
